spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:santaclothes
    username: sa
    password:
    initialization-mode: always

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
