spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: santa-clothes-api-server
  profiles:
    group:
      default: "local"
      local: "database-develop, external-api"
      real: "database-real, external-api"
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
pinocchio:
  images:
    path: /tmp/santaclothes